version: '3.8'

services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - minio
    volumes:
      - .:/app
    networks:
      - flask_network
    restart: on-failure

  minio:
    image: quay.io/minio/minio:RELEASE.2024-11-07T00-52-20Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./local/minio/data:/mnt/data
      - ./minio.config.env:/etc/config.env
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
    entrypoint: /bin/sh -c "minio server /mnt/data --console-address ':9090'"
    restart: unless-stopped  

networks:
  flask_network:
    driver: bridge

volumes:
  minio_data:
    driver: local
